export const categoryTranslations = {
    "Buy Apartment": "Покупка квартиры",
    "Childcare": "Детские расходы",
    "Clothing And Shoes": "Одежда и обувь",
    "Rent Per Month": "Аренда в месяц",
    "Markets": "Еда и напитки",
    "Restaurants": "Рестораны",
    "Salaries And Financing": "Зарплаты и финансы",
    "Sports And Leisure": "Спорт и досуг",
    "Transportation": "Транспорт",
    "Utilities Per Month": "Коммунальные услуги"
  };

  export const itemTranslations = {
    "Price per square meter to Buy Apartment Outside of City Center": "Цена за м² за покупку квартиры за пределами центра",
    "Price per square meter to Buy Apartment in City Center": "Цена за м² за покупку квартиры в центре города",
    "International Primary School, Yearly for 1 Child": "Международная начальная школа (год за 1 ребёнка)",
    "Private Preschool or Kindergarten, Monthly for 1 Child": "Частный детсад или ясли (месяц за 1 ребёнка)",
    "Pair of Jeans in a Chain Store Like George, H&M, Zara, etc.": "Джинсы в сетевых магазинах (George, H&M, Zara и др.)",
    "Pair of Leather Business Shoes": "Кожаные деловые туфли",
    "Pair of Running Shoes, Mid-Range Price": "Кроссовки средней ценовой категории",
    "Apples, 1 kg": "Яблоки, 1 кг",
    "Banana, 1 kg": "Бананы, 1 кг",
    "Beef Round or Equivalent Back Leg Red Meat, 1 kg": "Говядина (задняя часть), 1 кг",
    "Bottle of Wine, Mid-Range Price": "Бутылка вина средней цены",
    "Chicken Breasts, Boneless and Skinless, 1 kg": "Куриные грудки без костей и кожи, 1 кг",
    "Domestic Beer, 0.5 liter Bottle": "Местное пиво, бутылка 0.5 л",
    "Eggs, 12 pack": "Яйца, упаковка 12 шт",
    "Lettuce, 1 head": "Салат, 1 кочан",
    "Loaf of Fresh White Bread, 0.5 kg": "Буханка белого хлеба, 0.5 кг",
    "Local Cheese, 1 kg": "Местный сыр, 1 кг",
    "Milk, Regular,1 liter": "Молоко обычное, 1 литр",
    "Onion, 1 kg": "Лук, 1 кг",
    "Oranges, 1 kg": "Апельсины, 1 кг",
    "Pack of Cigarettes": "Пачка сигарет",
    "Potato, 1 kg": "Картофель, 1 кг",
    "White Rice, 1 kg": "Белый рис, 1 кг",
    "Tomato, 1 kg": "Томаты, 1 кг",
    "Water, 1.5 liter Bottle": "Вода, бутылка 1.5 л",
    "One bedroom apartment outside of city centre": "Квартира с 1 спальней за пределами центра",
    "One bedroom apartment in city centre": "Квартира с 1 спальней в центре",
    "Three bedroom apartment outside of city centre": "Квартира с 3 спальнями за пределами центра",
    "Three bedroom apartment in city centre": "Квартира с 3 спальнями в центре",
    "Cappuccino": "Капучино",
    "Coca-Cola, 0.33 liter Bottle": "Кока-Кола, бутылка 0.33 л",
    "Domestic Beer, 0.5 liter Draught": "Местное пиво, разливное 0.5 л",
    "Imported Beer, 0.33 liter Bottle": "Импортное пиво, бутылка 0.33 л",
    "McMeal at McDonalds or Alternative Combo Meal": "МакКомбо в McDonalds или аналогичный сет",
    "Meal for 2 People, Mid-range Restaurant, Three-course": "Ужин на двоих в ресторане среднего уровня (3 блюда)",
    "Meal in Inexpensive Restaurant": "Еда в недорогом ресторане",
    "Average Monthly Net Salary, After Tax": "Средняя месячная зарплата (чистыми)",
    "Cinema ticket, 1 Seat": "Билет в кино, 1 место",
    "Fitness Club, Monthly Fee for 1 Adult": "Абонемент в спортзал, в месяц за 1 взрослого",
    "Tennis Court Rent, 1 Hour on Weekend": "Аренда теннисного корта, 1 час в выходные",
    "Gasoline, 1 liter": "Бензин, 1 литр",
    "Monthly Pass, Regular Price": "Месячный проездной",
    "One-way Ticket, Local Transport": "Билет на общественный транспорт, в одну сторону",
    "Taxi, price for 1 hour Waiting, Normal Tariff": "Такси, ожидание 1 час (обычный тариф)",
    "Taxi, price for 1 km, Normal Tariff": "Такси, цена за 1 км (обычный тариф)",
    "Taxi Start, Normal Tariff": "Такси, посадка (обычный тариф)",
    "Volkswagen Golf 1.4 90 KW Trendline (Or Equivalent New Car)": "Volkswagen Golf 1.4 или аналогичный новый авто",
    "Prepaid Mobile Tariff Local, price per 1 min, No Discounts or Plans": "Мобильная связь по предоплате, 1 мин без скидок",
    "Basic utilities for 85 square meter Apartment including Electricity, Heating or Cooling, Water and Garbage": "Коммуналка для квартиры 85 м² (вода, свет, отопление, вывоз мусора)",
    "Internet, 60 Mbps or More, Unlimited Data, Cable/ADSL": "Интернет 60 Мбит/с и выше, безлимитный",
    "Water, 0.33 liter Bottle": "Вода, бутылка 0.33 л",
    "Summer Dress in a Chain Store Like George, H&M, Zara, etc.": "Летнее платье в сетевых магазинах (George, H&M, Zara и др.)",
    "Mortgage Interest Rate in Percentages for 20 Years Fixed-Rate, Yearly, Fixed-Rate": "Ипотечная ставка на 20 лет, фиксированная, годовая"
  };